version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: stratify_backend/Dockerfile
    volumes:
      - ./stratify_backend:/stratify_backend
      - /stratify_backend/.venv
    ports:
      - 80:8000
    networks:
      - stratify-backend
    env_file:
      - .env
    depends_on:
      db_postgres:
        condition: service_healthy

  db_postgres:
    image: postgres:15.3
    expose:
      - 5432
    networks:
      - stratify-backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stratify-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    networks:
      - stratify-backend
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db_postgres
    restart: always

networks:
  stratify-backend:
    name: stratify-backend
    driver: bridge
