name: Build and Deploy to ECR and ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract image name
        id: vars
        run: |
          echo "REPO_URI=${{ secrets.ECR_REPOSITORY }}" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t $REPO_URI:$IMAGE_TAG -f backend/Dockerfile .
          docker push $REPO_URI:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster prod-cluster \
            --service prod-backend \
            --force-new-deployment
